### ISSUE TITLE
Playbook hangs on 'Join cluster'

### ISSUE THREAD

**Issue by bostone** [sjenning/kubeadm-playbook#1]
I have 1 master and 2 minion nodes which are reflected in hosts file. I also modifies `all` and set `kubeadm_network_addon_url: https://git.io/weave-kube-1.6`. When I run script is simply never goes past this line
```
TASK [node : Join cluster]
```

**Comment by sjenning** [comment]
I'm not really looking to offer support for this.  If you find an issue, PRs are welcome.
